CREATE TABLE `blog_categories` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`slug` varchar(100) NOT NULL,
	`description` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `blog_categories_id` PRIMARY KEY(`id`),
	CONSTRAINT `blog_categories_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `blog_posts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`excerpt` text,
	`content` text NOT NULL,
	`featuredImage` varchar(500),
	`categoryId` int,
	`authorId` int,
	`metaTitle` varchar(255),
	`metaDescription` text,
	`published` boolean DEFAULT false,
	`publishedAt` timestamp,
	`views` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blog_posts_id` PRIMARY KEY(`id`),
	CONSTRAINT `blog_posts_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `interactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int NOT NULL,
	`userId` int,
	`type` enum('ligacao','whatsapp','email','visita','reuniao','proposta','nota','status_change') NOT NULL,
	`subject` varchar(255),
	`description` text,
	`metadata` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `interactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`email` varchar(320),
	`phone` varchar(20),
	`whatsapp` varchar(20),
	`source` enum('site','whatsapp','instagram','facebook','indicacao','portal_zap','portal_vivareal','portal_olx','google','outro') DEFAULT 'site',
	`stage` enum('novo','contato_inicial','qualificado','visita_agendada','visita_realizada','proposta','negociacao','fechado_ganho','fechado_perdido','sem_interesse') NOT NULL DEFAULT 'novo',
	`buyerProfile` enum('investidor','primeira_casa','upgrade','curioso','indeciso'),
	`interestedPropertyId` int,
	`budgetMin` int,
	`budgetMax` int,
	`preferredNeighborhoods` text,
	`preferredPropertyTypes` text,
	`notes` text,
	`tags` text,
	`assignedTo` int,
	`score` int DEFAULT 0,
	`priority` enum('baixa','media','alta','urgente') DEFAULT 'media',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastContactedAt` timestamp,
	`convertedAt` timestamp,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `properties` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`referenceCode` varchar(50),
	`propertyType` enum('casa','apartamento','cobertura','terreno','comercial','rural','lancamento') NOT NULL,
	`transactionType` enum('venda','locacao','ambos') NOT NULL,
	`address` varchar(255),
	`neighborhood` varchar(100),
	`city` varchar(100),
	`state` varchar(2),
	`zipCode` varchar(10),
	`latitude` varchar(50),
	`longitude` varchar(50),
	`salePrice` int,
	`rentPrice` int,
	`condoFee` int,
	`iptu` int,
	`bedrooms` int,
	`bathrooms` int,
	`suites` int,
	`parkingSpaces` int,
	`totalArea` int,
	`builtArea` int,
	`features` text,
	`images` text,
	`mainImage` varchar(500),
	`status` enum('disponivel','reservado','vendido','alugado','inativo') NOT NULL DEFAULT 'disponivel',
	`featured` boolean DEFAULT false,
	`published` boolean DEFAULT true,
	`metaTitle` varchar(255),
	`metaDescription` text,
	`slug` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdBy` int,
	CONSTRAINT `properties_id` PRIMARY KEY(`id`),
	CONSTRAINT `properties_referenceCode_unique` UNIQUE(`referenceCode`),
	CONSTRAINT `properties_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `site_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyName` varchar(255),
	`companyDescription` text,
	`companyLogo` varchar(500),
	`realtorName` varchar(255),
	`realtorPhoto` varchar(500),
	`realtorBio` text,
	`realtorCreci` varchar(50),
	`phone` varchar(20),
	`whatsapp` varchar(20),
	`email` varchar(320),
	`address` text,
	`instagram` varchar(255),
	`facebook` varchar(255),
	`youtube` varchar(255),
	`tiktok` varchar(255),
	`linkedin` varchar(255),
	`siteTitle` varchar(255),
	`siteDescription` text,
	`siteKeywords` text,
	`googleAnalyticsId` varchar(50),
	`facebookPixelId` varchar(50),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `site_settings_id` PRIMARY KEY(`id`)
);
